(package "flymake-ziglint"
         "0.1.0"
         "Flymake for ziglint")

(website-url "https://github.com/flymake/flymake-ziglint")
(keywords "tools")

(package-file "flymake-ziglint.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "flymake-easy")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
